// Sprint 62.P2 — defensive post-processor that swaps common English sales /
// finance jargon → Russian equivalents in AI-generated text fields.
//
// Why: the system prompt now explicitly forbids English jargon, but the LLM
// occasionally still leaks "next step" / "value proposition" / "implication
// question" / "elevator pitch" because its training data is English-heavy
// for sales methodology. This layer is the safety net AFTER the prompt
// directive — runs on every string field of the assistant card / analysis
// before it's sent to the UI.
//
// Design notes:
//   • Word-bounded matching (\b) so we don't touch substrings inside Russian
//     words. JS \b doesn't work for Cyrillic letters, so the matchers use
//     explicit non-letter lookarounds to avoid mid-word matches.
//   • Case-insensitive but case-preserved: «Next step» → «Следующий шаг»,
//     «next step» → «следующий шаг», «NEXT STEP» → «Следующий шаг».
//   • Whitelist of intentional English (KPI, ROI, LTV, CAC, MRR, ARR, GMV,
//     EBITDA, P&L, SPIN, B2B, B2C, SaaS, NDA, AI) — those are never touched
//     because they're acronyms used as-is in Russian business.
//   • Product / brand names (Zoom, Telegram, WhatsApp, OpenAI, GitHub, etc.)
//     don't appear in this jargon table, so they pass through untouched.

interface JargonRule {
  // Regex pattern. Must be /…/giu — global, case-insensitive, unicode.
  pattern: RegExp;
  // Replacement string. Use $1, $2 if pattern has capture groups.
  // Preserve sentence-case via casePreserve helper if first letter matters.
  replacement: string;
}

// Lookarounds: (?<![\p{L}\p{N}_]) and (?![\p{L}\p{N}_]) ensure we don't
// match inside another word (e.g. don't touch "nextstep" or "запретnext step").
const LB = '(?<![\\p{L}\\p{N}_])';
const RB = '(?![\\p{L}\\p{N}_])';

const RULES: JargonRule[] = [
  // ── Sales methodology ───────────────────────────────────────────────────
  { pattern: new RegExp(`${LB}next\\s+step${RB}`, 'giu'),                  replacement: 'следующий шаг' },
  { pattern: new RegExp(`${LB}next-step${RB}`, 'giu'),                     replacement: 'следующий шаг' },
  { pattern: new RegExp(`${LB}value\\s+proposition${RB}`, 'giu'),          replacement: 'ценностное предложение' },
  { pattern: new RegExp(`${LB}elevator\\s+pitch${RB}`, 'giu'),             replacement: 'краткий питч' },
  { pattern: new RegExp(`${LB}implication\\s+question${RB}`, 'giu'),       replacement: 'вопрос о последствиях' },
  { pattern: new RegExp(`${LB}implication${RB}`, 'giu'),                   replacement: 'последствия' },
  { pattern: new RegExp(`${LB}perceived\\s+value${RB}`, 'giu'),            replacement: 'воспринимаемая ценность' },
  { pattern: new RegExp(`${LB}pain\\s+point${RB}`, 'giu'),                 replacement: 'болевая точка' },
  { pattern: new RegExp(`${LB}dissatisfaction${RB}`, 'giu'),               replacement: 'неудовлетворённость' },
  { pattern: new RegExp(`${LB}closing${RB}`, 'giu'),                       replacement: 'закрытие сделки' },
  { pattern: new RegExp(`${LB}follow-up${RB}`, 'giu'),                     replacement: 'повторное касание' },
  { pattern: new RegExp(`${LB}follow\\s+up${RB}`, 'giu'),                  replacement: 'повторное касание' },

  // ── Finance jargon (only the unambiguous ones; keep MRR/ARR/LTV/CAC) ────
  { pattern: new RegExp(`${LB}cashflow${RB}`, 'giu'),                      replacement: 'денежный поток' },
  { pattern: new RegExp(`${LB}cash\\s+flow${RB}`, 'giu'),                  replacement: 'денежный поток' },
  { pattern: new RegExp(`${LB}opex\\s+breakdown${RB}`, 'giu'),             replacement: 'структура операционных расходов' },
  { pattern: new RegExp(`${LB}retention${RB}`, 'giu'),                     replacement: 'удержание клиентов' },
  { pattern: new RegExp(`${LB}recurring\\s+revenue${RB}`, 'giu'),          replacement: 'повторяющаяся выручка' },

  // ── UI / product terms ──────────────────────────────────────────────────
  { pattern: new RegExp(`${LB}AI\\s+conversation${RB}`, 'giu'),            replacement: 'AI-диалог' },
  { pattern: new RegExp(`${LB}onboarding${RB}`, 'giu'),                    replacement: 'подключение' },
  { pattern: new RegExp(`${LB}one-pager${RB}`, 'giu'),                     replacement: 'ванпейджер' },
  { pattern: new RegExp(`${LB}onepager${RB}`, 'giu'),                      replacement: 'ванпейджер' },
  { pattern: new RegExp(`${LB}landing\\s+page${RB}`, 'giu'),               replacement: 'посадочная страница' },
  { pattern: new RegExp(`${LB}pitch\\s+deck${RB}`, 'giu'),                 replacement: 'инвестиционная презентация' },

  // ── Mixed hyphenations: «wedding-агентства» → «свадебные агентства» ─────
  // These are very specific to the demo project (Luce Silva / wedding venue).
  // The hybrid form is generated by AI when it doesn't know the Russian
  // adjective form; map a small set explicitly. Pattern requires a
  // Cyrillic word right after the hyphen so we don't accidentally touch
  // English-only phrases.
  { pattern: new RegExp(`${LB}wedding-агентств`, 'giu'),                   replacement: 'свадебные агентств' },
  { pattern: new RegExp(`${LB}wedding-площад`, 'giu'),                     replacement: 'свадебные площад' },
];

/**
 * Preserve sentence-case: if the matched English jargon started with an
 * uppercase letter, capitalize the first letter of the replacement.
 */
function preserveCase(matched: string, replacement: string): string {
  if (!matched || !replacement) return replacement;
  const firstChar = matched.charAt(0);
  if (firstChar === firstChar.toUpperCase() && firstChar !== firstChar.toLowerCase()) {
    return replacement.charAt(0).toUpperCase() + replacement.slice(1);
  }
  return replacement;
}

/**
 * Translates English business jargon → Russian inside `text`. Returns the
 * same string if no rules matched. Idempotent — running twice has the same
 * result as running once.
 */
export function russianizeText(text: string | null | undefined): string | null | undefined {
  if (text === null || text === undefined) return text;
  if (typeof text !== 'string' || text.length === 0) return text;
  let out = text;
  for (const rule of RULES) {
    out = out.replace(rule.pattern, (matched) => preserveCase(matched, rule.replacement));
  }
  return out;
}

/**
 * Deep-traverses an object/array tree and applies russianizeText to every
 * string leaf. Non-string fields pass through unchanged. Used to scrub AI
 * card outputs (situation, mainQuestion, backupQuestions[], whatToDo[], …)
 * in one shot before returning to the client.
 *
 * NOTE: this mutates a copy, not the input. Safe to call on AI response
 * objects.
 */
export function russianizeDeep<T>(value: T): T {
  if (value === null || value === undefined) return value;
  if (typeof value === 'string') {
    return (russianizeText(value) ?? '') as unknown as T;
  }
  if (Array.isArray(value)) {
    return value.map((v) => russianizeDeep(v)) as unknown as T;
  }
  if (typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) {
      out[k] = russianizeDeep(v);
    }
    return out as T;
  }
  return value;
}

/**
 * Whitelist export — if a downstream caller needs to skip russianization for
 * a specific field (e.g. raw transcript echoed back), it can compare against
 * this list of patterns. Currently unused but kept for documentation.
 */
export const RUSSIANIZED_PATTERNS = RULES.map((r) => r.pattern.source);
